---
abstract: 'Lazier Attributes.'
author:
  - 'Robert Acock <thisusedtobeanemail@gmail.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-LazierAttributes
no_index:
  directory:
    - t
    - inc
provides:
  MooX::LazierAttributes:
    file: lib/MooX/LazierAttributes.pm
    version: '1.01'
resources:
  repository: https://github.com/ThisUsedToBeAnEmail/MooX-LazierAttributes.git
version: '1.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
